const KEY="bb_pwa_v1";
let db=JSON.parse(localStorage.getItem(KEY)||"null")||{
  menu:[
    {id:1,name:"Плов",price:25,cost:12,cat:"Вторые блюда",emoji:"🍚"},
    {id:2,name:"Салат",price:10,cost:4,cat:"Салаты",emoji:"🥗"},
    {id:3,name:"Напиток",price:5,cost:2,cat:"Напитки",emoji:"🥤"}
  ],orders:[],expenses:[],recipes:[],nextOrder:1001
};
let cart=[];
const save=()=>localStorage.setItem(KEY,JSON.stringify(db));
const money=n=>`${Number(n||0).toFixed(2).replace(".00","")} SAR`;
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
function toast(t){const x=document.getElementById("toast");x.textContent=t;x.style.display="block";clearTimeout(window.tt);window.tt=setTimeout(()=>x.style.display="none",1800)}
function go(id,btn){document.querySelectorAll(".section").forEach(x=>x.classList.remove("active"));document.getElementById(id).classList.add("active");document.querySelectorAll(".nav button").forEach(x=>x.classList.remove("active"));if(btn)btn.classList.add("active");if(id==="orders")renderMenu();if(id==="history")renderOrders();if(id==="menu")renderAdminMenu();if(id==="finance")renderFinance()}
function renderMenu(){const g=document.getElementById("menuGrid");g.innerHTML=db.menu.map(m=>`<div class="card menu-card"><div class="menu-img">${m.emoji||"🍽️"}</div><div class="menu-body"><div class="row"><b>${esc(m.name)}</b><span class="price">${money(m.price)}</span></div><div class="muted">${esc(m.cat||"")}</div><button class="btn" style="width:100%;margin-top:9px" onclick="addCart(${m.id})">Добавить</button></div></div>`).join("")||`<div class="empty">Добавьте блюда в разделе «Меню».</div>`;renderCart()}
function addCart(id){const m=db.menu.find(x=>x.id===id);if(!m)return;let x=cart.find(x=>x.id===id);if(x)x.qty++;else cart.push({id,qty:1});renderCart();toast("Добавлено")}
function changeQty(id,d){const x=cart.find(x=>x.id===id);if(!x)return;x.qty+=d;if(x.qty<=0)cart=cart.filter(y=>y.id!==id);renderCart()}
function clearCart(){cart=[];renderCart()}
function renderCart(){const c=document.getElementById("cart"), total=cart.reduce((s,x)=>{const m=db.menu.find(m=>m.id===x.id);return s+(m?m.price*x.qty:0)},0);document.getElementById("cartCount").textContent=cart.reduce((s,x)=>s+x.qty,0)+" поз.";document.getElementById("cartTotal").textContent=money(total);c.innerHTML=cart.length?cart.map(x=>{const m=db.menu.find(m=>m.id===x.id);return `<div class="item"><div class="row"><b>${esc(m.name)}</b><b>${money(m.price*x.qty)}</b></div><div class="row" style="margin-top:6px"><span class="muted">${money(m.price)} × ${x.qty}</span><span><button class="btn light small" onclick="changeQty(${x.id},-1)">−</button> <button class="btn light small" onclick="changeQty(${x.id},1)">+</button></span></div></div>`}).join(""):`<div class="empty">Выберите блюдо из меню.</div>`}
function acceptOrder(){if(!cart.length){toast("Сначала добавьте блюдо");return}const items=cart.map(x=>{const m=db.menu.find(m=>m.id===x.id);return {id:m.id,name:m.name,qty:x.qty,price:m.price,cost:m.cost||0}});const total=items.reduce((s,x)=>s+x.price*x.qty,0),cost=items.reduce((s,x)=>s+x.cost*x.qty,0);db.orders.unshift({id:db.nextOrder++,date:new Date().toISOString(),items,total,cost,status:"Новый"});save();cart=[];renderCart();toast("Заказ принят");setTimeout(()=>go("history",document.querySelector('[data-go="history"]')),250)}
function renderOrders(){const el=document.getElementById("ordersList");el.innerHTML=db.orders.length?db.orders.map(o=>`<div class="item"><div class="row"><b>Заказ #${o.id}</b><span class="pill">${esc(o.status)}</span></div><div class="muted">${new Date(o.date).toLocaleString()}</div><div style="margin-top:8px">${o.items.map(i=>`${esc(i.name)} × ${i.qty}`).join(", ")}</div><div class="row" style="margin-top:8px"><b>${money(o.total)}</b><button class="btn small ${o.status==="Выполнен"?"light":"ok"}" onclick="toggleOrder(${o.id})">${o.status==="Выполнен"?"Вернуть":"Выполнен"}</button></div></div>`).join(""):`<div class="empty">Заказов пока нет.</div>`}
function toggleOrder(id){const o=db.orders.find(x=>x.id===id);if(o)o.status=o.status==="Выполнен"?"Новый":"Выполнен";save();renderOrders()}
function renderAdminMenu(){const el=document.getElementById("adminMenu");el.innerHTML=db.menu.length?db.menu.map(m=>`<div class="item"><div class="row"><b>${esc(m.emoji||"🍽️")} ${esc(m.name)}</b><b>${money(m.price)}</b></div><div class="muted">${esc(m.cat)} • Себестоимость: ${money(m.cost)}</div><div class="actions"><button class="btn light small" onclick="openMenuForm(${m.id})">Изменить</button><button class="btn danger small" onclick="deleteMenu(${m.id})">Удалить</button></div></div>`).join(""):`<div class="empty">Меню пустое.</div>`}
function openMenuForm(id){const m=id?db.menu.find(x=>x.id===id):{name:"",price:"",cost:"",cat:"",emoji:"🍽️"};openModal(`<h2>${id?"Изменить блюдо":"Новое блюдо"}</h2><div class="field"><label>Название</label><input id="fName" value="${esc(m.name)}"></div><div class="field"><label>Цена продажи, SAR</label><input id="fPrice" type="number" step="0.01" value="${m.price}"></div><div class="field"><label>Себестоимость, SAR</label><input id="fCost" type="number" step="0.01" value="${m.cost}"></div><div class="field"><label>Категория</label><input id="fCat" value="${esc(m.cat)}"></div><div class="field"><label>Эмодзи</label><input id="fEmoji" value="${esc(m.emoji||"🍽️")}"></div><div class="actions"><button class="btn" onclick="saveMenu(${id||0})">Сохранить</button><button class="btn light" onclick="closeModal()">Отмена</button></div>`)}
function saveMenu(id){const name=document.getElementById("fName").value.trim();if(!name)return toast("Введите название");const obj={name,price:+document.getElementById("fPrice").value||0,cost:+document.getElementById("fCost").value||0,cat:document.getElementById("fCat").value.trim(),emoji:document.getElementById("fEmoji").value.trim()||"🍽️"};if(id){Object.assign(db.menu.find(x=>x.id===id),obj)}else{obj.id=Date.now();db.menu.push(obj)}save();closeModal();renderAdminMenu();renderMenu();toast("Сохранено")}
function deleteMenu(id){if(!confirm("Удалить блюдо?"))return;db.menu=db.menu.filter(x=>x.id!==id);cart=cart.filter(x=>x.id!==id);save();renderAdminMenu();renderMenu()}
function openExpenseForm(){openModal(`<h2>Добавить расход</h2><div class="field"><label>Название</label><input id="eName" placeholder="Продукты, упаковка..."></div><div class="field"><label>Сумма, SAR</label><input id="eAmount" type="number" step="0.01"></div><div class="field"><label>Комментарий</label><input id="eNote"></div><div class="actions"><button class="btn" onclick="saveExpense()">Сохранить</button><button class="btn light" onclick="closeModal()">Отмена</button></div>`)}
function saveExpense(){const name=document.getElementById("eName").value.trim()||"Расход";const amount=+document.getElementById("eAmount").value||0;db.expenses.unshift({id:Date.now(),date:new Date().toISOString(),name,amount,note:document.getElementById("eNote").value.trim()});save();closeModal();renderFinance();toast("Расход добавлен")}
function deleteExpense(id){db.expenses=db.expenses.filter(x=>x.id!==id);save();renderFinance()}
function openRecipeForm(){if(!db.menu.length)return toast("Сначала добавьте блюдо");openModal(`<h2>Техкарта</h2><div class="field"><label>Блюдо</label><select id="rMenu">${db.menu.map(m=>`<option value="${m.id}">${esc(m.name)}</option>`).join("")}</select></div><div class="field"><label>Ингредиенты</label><textarea id="rIng" style="width:100%;min-height:120px;border:1px solid var(--line);border-radius:10px;padding:10px" placeholder="Рис — 200 г — 3 SAR&#10;Мясо — 150 г — 7 SAR&#10;Морковь — 100 г — 1 SAR"></textarea></div><div class="field"><label>Общая себестоимость порции, SAR</label><input id="rCost" type="number" step="0.01"></div><div class="actions"><button class="btn" onclick="saveRecipe()">Сохранить</button><button class="btn light" onclick="closeModal()">Отмена</button></div>`)}
function saveRecipe(){const menuId=+document.getElementById("rMenu").value;const cost=+document.getElementById("rCost").value||0;const ingredients=document.getElementById("rIng").value.trim();const m=db.menu.find(x=>x.id===menuId);if(m)m.cost=cost;db.recipes.unshift({id:Date.now(),menuId,ingredients,cost});save();closeModal();renderFinance();renderAdminMenu();toast("Техкарта сохранена")}
function deleteRecipe(id){db.recipes=db.recipes.filter(x=>x.id!==id);save();renderFinance()}
function renderFinance(){const sales=db.orders.reduce((s,o)=>s+o.total,0),cost=db.orders.reduce((s,o)=>s+o.cost,0),expenses=db.expenses.reduce((s,e)=>s+e.amount,0);document.getElementById("sSales").textContent=money(sales);document.getElementById("sCost").textContent=money(cost);document.getElementById("sExpenses").textContent=money(expenses);document.getElementById("sProfit").textContent=money(sales-cost-expenses);document.getElementById("expenseList").innerHTML=db.expenses.length?db.expenses.map(e=>`<div class="item"><div class="row"><b>${esc(e.name)}</b><b>${money(e.amount)}</b></div><div class="muted">${new Date(e.date).toLocaleDateString()} ${esc(e.note||"")}</div><div class="actions"><button class="btn danger small" onclick="deleteExpense(${e.id})">Удалить</button></div></div>`).join(""):`<div class="empty">Расходов нет.</div>`;document.getElementById("recipeList").innerHTML=db.recipes.length?db.recipes.map(r=>{const m=db.menu.find(x=>x.id===r.menuId);return `<div class="item"><div class="row"><b>${esc(m?.name||"Блюдо удалено")}</b><b>${money(r.cost)}</b></div><div class="muted" style="white-space:pre-line;margin-top:7px">${esc(r.ingredients)}</div><div class="actions"><button class="btn danger small" onclick="deleteRecipe(${r.id})">Удалить</button></div></div>`}).join(""):`<div class="empty">Техкарт нет.</div>`}
function openModal(html){document.getElementById("sheet").innerHTML=html;document.getElementById("modal").classList.add("show")}
function closeModal(){document.getElementById("modal").classList.remove("show")}
document.getElementById("modal").addEventListener("click",e=>{if(e.target.id==="modal")closeModal()});
renderMenu();renderOrders();renderAdminMenu();renderFinance();
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js").catch(()=>{}));
